# Generated by Django 5.0.7 on 2024-09-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_cart_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='goods',
            new_name='good',
        ),
    ]
